### ISSUE TITLE
Java error on startup 

### ISSUE THREAD

**Issue by batmilchone** [kaloyan-raev/chitanka4kindle#15]
Здравейте от няколко седмици получавам следната грешка при стартиране на приложението. Ще се радвам на помощ.

parsing: http://chitanka.info/catalog.opds

= name. raev kaloyan. kindle chitanka.OpdsPage.parse(OpdsPage .java:121)

«t name_raev.kaloyan.kindle .chitanka.OpdsPage.parseFirstPage(OpdsPage java:95)

at name raev kaloyan kindle .chitanka. OpdsPage.parsePagesCount(OpdsPage java: 76)

at name_raev.kaloyan. kindle chitanka.OpdsPage.getltemsCount/OpdsPage .java:60)

at name_raev.kaloyan. kindle .chitanka.OpdsPage.getitems(/OpdsPage.java:161)

at name_raev.kaloyan.kindle.chitanka.screen.HomeScreen.addLinks(Home Screen java: 70)

at name_raev.kaloyan.kandle .chitanka.screen.HomeScreen.createContent(Home Screen java:44)

at name_raev.kaloyan. kindle .chitanka.screen.Screen.displa ‘Screen.java:94)
Здравейте от няколко седмици при стартиране на читанка ми излиза следната грешка:
at name_raev.kaloyan.kindle.chitanka.ConnectivityManagerS1 _connected(ConnectiityManager va:

at com.amazon.kindle.kindlet.internal. net. vb.run(kvb:63)

at edu_emory.mathcs.backport java.uti_ concurrent. Executors$RunnableAdapter.caliigr-63)
at edu.emory.mathcs.backport java .uti_concurrent. Future Task. run(ez:491)

at edu.emory.mathc s.backport.java.uti_ concurrent. ThreadPoolExecutor. BWip:959)

at edu.emory.mathcs.backport java.utiL concurrent. ThreadPoolExecutor$Worker.run(j:803)
at java lang. Thread.run(Thread java:988)

at java.lang Thread. startup(Thread java:1065)

Caused by: java.io.\OException: Not in GZIP format

at java_uti.zip.GZiPinputStream.readHeader(GZIPinputStream java:t 33)

at pva_uti zp.GZiPinputSt
at pve vil zp.GZiPinputStr

eam.<init>{(GZIPinputStream .java:60)
eam.<init>{GZIPinputStream .java:70)

at name_raev.kaloyan.kindle.chitanka. utils. Network.getinputStream(Network java:77)

at name_raev.kaloyan.kindle .chitanka. utils. Network getinputStream(Network java:

at name_.raev.kaloyan.kindle .chitanka.OpdsPage.parse| pdsPage.java:119)

.. 15 more
Модела е Kindle 3 wifi + 3g s/n B006 прикачвам и линк към снимката [Error](https://drive.google.com/file/d/1MqTkvFYj3fPzKlLS8eDeH3jdyoU124WK/view?usp=drivesdk)

**Comment by rakovm** [comment]
Привет, 
Потвърждавам. От повече от месец дядо ми изпитва абсолютно същия проблем. Интересното е, че явно са променили нещо в самата chitanka. Г-н Раев, може ли да се направи нещо по въпроса?
